alias be="bundle exec"
alias brails="bundle exec rails"
alias brake="bundle exec rake"
alias brspec="bundle exec rspec"
alias appup="foreman start -f Procfile.dev"
alias pumaappup="foreman start -f Procfile-puma.dev"
alias rspecfail="bundle exec rspec spec/ --only-failures"
alias zdebug="tail -f log/development.log | grep ZZZZ"
alias speccompile="rm -rf /Users/phillipgray/code/scf/public/packs-test && RAILS_ENV=test bundle exec rails webpacker:compile"
alias specc="speccompile"
alias devcompile="rm -rf /Users/phillipgray/code/scf/public/packs && RAILS_ENV=development bundle exec rails webpacker:compile"
alias devc="devcompile"
